version: "3.7"
services:
    app:
        build:
            args:
                user: worker
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: roster
        container_name: roster-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - roster

    nginx:
        image: nginx:alpine
        container_name: roster-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - roster

networks:
    roster:
        driver: bridge
